# Generated by Django 3.2.9 on 2023-02-22 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='HistoricalUser',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
