# Generated by Django 3.2.9 on 2023-03-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='mision',
            field=models.TextField(verbose_name='Misión de la Empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='vision',
            field=models.TextField(verbose_name='Visión de la Empresa'),
        ),
    ]
