# Generated by Django 3.2.9 on 2023-02-13 18:20

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menorandum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de Archivo')),
                ('texto', ckeditor.fields.RichTextField()),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electronico')),
                ('archivos', models.FileField(upload_to='Archivos/')),
                ('date_expiring', models.DateField(verbose_name='Fecha de Expiracion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
