# Generated by Django 3.2.9 on 2023-02-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorandum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menorandum',
            options={'verbose_name': 'Memorandum', 'verbose_name_plural': 'Memorandums'},
        ),
        migrations.AddField(
            model_name='menorandum',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
