# Generated by Django 3.2.9 on 2023-02-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorandum', '0002_auto_20230217_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menorandum',
            name='archivos',
            field=models.FileField(blank=True, null=True, upload_to='Archivos/'),
        ),
        migrations.AlterField(
            model_name='menorandum',
            name='date_expiring',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Expiracion'),
        ),
    ]
