# Generated by Django 3.2.9 on 2023-02-20 03:10

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorandum', '0003_auto_20230217_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menorandum',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='menorandum',
            name='texto',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
