# Generated by Django 3.2.9 on 2023-02-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorandum', '0004_auto_20230219_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menorandum',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Correo Electronico'),
        ),
    ]
