# Generated by Django 3.2.9 on 2023-03-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorandum', '0006_auto_20230226_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menorandum',
            name='archivos',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
